package com.sample.rules
 
import com.sample.State;

declare type State
	@propertyChangeSupport
end

rule "Bootstrap"
	when
		a: State(name == "A", state == State.NOTRUN)
	then
		System.out.println(a.getName() + " finished");
		a.setState(State.FINISHED);
		// update(a);
end
		
rule "A to B"
	when
		State(name == "A", state == State.FINISHED)
		b: State(name == "B", state == State.NOTRUN)
	then
		System.out.println(b.getName() + " finished");
		b.setState(State.FINISHED);
		// update(b);
end
 
rule "B to C"
	when
		State(name == "B", state == State.FINISHED)
		c: State(name == "C", state == State.NOTRUN)
	then
		System.out.println(c.getName() + " finished");
		c.setState(State.FINISHED);
		// update(c);
end
		
rule "B to D"
	salience 10
	when
		State(name == "B", state == State.FINISHED)
		d: State(name == "D", state == State.NOTRUN)
	then
		System.out.println(d.getName() + " finished");
		d.setState(State.FINISHED);
		// update(d);
end